<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\HornsAndHoovesCrm.Core\HornsAndHoovesCrm.Core.csproj" />
      <ProjectReference Include="..\HornsAndHoovesCrm.Modules.ReferenceData.Contracts\HornsAndHoovesCrm.Modules.ReferenceData.Contracts.csproj" />
      <ProjectReference Include="..\HornsAndHoovesCrm.Modules.ReferenceData.DataAccess\HornsAndHoovesCrm.Modules.ReferenceData.DataAccess.csproj" />
    </ItemGroup>

</Project>
