<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\HornsAndHoovesCrm.Core\HornsAndHoovesCrm.Core.csproj" />
      <ProjectReference Include="..\HornsAndHoovesCrm.ReferenceData.Admin.Contracts\HornsAndHoovesCrm.ReferenceData.Admin.Contracts.csproj" />
      <ProjectReference Include="..\HornsAndHoovesCrm.ReferenceData.DataAccess\HornsAndHoovesCrm.ReferenceData.DataAccess.csproj" />
    </ItemGroup>

</Project>
