<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\HornsAndHoovesCrm.Core\HornsAndHoovesCrm.Core.csproj" />
      <ProjectReference Include="..\HornsAndHoovesCrm.Modules.EntityFramework\HornsAndHoovesCrm.Modules.EntityFramework.csproj" />
      <ProjectReference Include="..\HornsAndHoovesCrm.ReferenceData.Domain.Shared\HornsAndHoovesCrm.ReferenceData.Domain.Shared.csproj" />
      <ProjectReference Include="..\HornsAndHoovesCrm.ReferenceData.Domain\HornsAndHoovesCrm.ReferenceData.Domain.csproj" />
    </ItemGroup>

</Project>
