<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\HornsAndHoovesCrm.AspNetCore.Jwt\HornsAndHoovesCrm.AspNetCore.Jwt.csproj" />
      <ProjectReference Include="..\HornsAndHoovesCrm.Core\HornsAndHoovesCrm.Core.csproj" />
      <ProjectReference Include="..\HornsAndHoovesCrm.Modules.Identity.Auth\HornsAndHoovesCrm.Modules.Identity.Auth.csproj" />
      <ProjectReference Include="..\HornsAndHoovesCrm.Modules.Identity\HornsAndHoovesCrm.Modules.Identity.csproj" />
    </ItemGroup>

</Project>
