<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <PropertyGroup>
        <OpenApiDocumentsDirectory>./</OpenApiDocumentsDirectory>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\HornsAndHoovesCrm.Modules.OpenApi\HornsAndHoovesCrm.Modules.OpenApi.csproj" />
      <ProjectReference Include="..\HornsAndHoovesCrm.Modules.Scalar\HornsAndHoovesCrm.Modules.Scalar.csproj" />
    </ItemGroup>

</Project>
